//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

pub mod prelude::*;

pub mod attendance;
pub mod cases;
pub mod contacts;
pub mod files;
pub mod news;
pub mod notifications;
pub mod reports_analytics;
pub mod staff;
pub mod summaries;
pub mod themes;
pub mod users;
