//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

pub use super::attendance::Entity as Attendance;
pub use super::cases::Entity as Cases;
pub use super::contacts::Entity as Contacts;
pub use super::files::Entity as Files;
pub use super::news::Entity as News;
pub use super::notifications::Entity as Notifications;
pub use super::reports_analytics::Entity as ReportsAnalytics;
pub use super::staff::Entity as Staff;
pub use super::summaries::Entity as Summaries;
pub use super::themes::Entity as Themes;
pub use super::users::Entity as Users;
